spring:
  application:
    name: arenapay
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/arenapay
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  flyway:
    batch: true
logging:
  level:
    org.flywaydb: DEBUG